---
include:
  - board: nice_nano//zmk
    shield: corne_left nice_oled
    snippet: studio-rpc-usb-uart

  - board: nice_nano//zmk
    shield: corne_right nice_oled

  - board: nice_nano//zmk
    shield: settings_reset