# ZMK Studio config
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n

# RGB config
CONFIG_ZMK_RGB_UNDERGLOW=y
# Turn off RGB when keyboard enters idle
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y

# OLED config
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
