# RGB config
CONFIG_ZMK_RGB_UNDERGLOW=y
# Turn off RGB when keyboard enters idle
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y

# OLED config — nice_oled widgets
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
